export const DESTINATIONS = [
  {
    id: "bali",
    name: "Bali",
    country: "Indonesia",
    style: "relaxation",
    continent: "Asia",
    emoji: "🌴",
    tagline: "Beaches, yoga retreats & spa resorts",
    gradient: "linear-gradient(135deg, #34d399, #059669)",
  },
  {
    id: "japan",
    name: "Japan",
    country: "Japan",
    style: "relaxation",
    continent: "Asia",
    emoji: "⛩️",
    tagline: "Temples, onsen & serene gardens",
    gradient: "linear-gradient(135deg, #f472b6, #db2777)",
  },
  {
    id: "maldives",
    name: "Maldives",
    country: "Maldives",
    style: "relaxation",
    continent: "Asia",
    emoji: "🏝️",
    tagline: "Overwater villas & crystal waters",
    gradient: "linear-gradient(135deg, #38bdf8, #0284c7)",
  },
  {
    id: "thailand",
    name: "Thailand",
    country: "Thailand",
    style: "budget",
    continent: "Asia",
    emoji: "🛕",
    tagline: "Street food, temples & islands",
    gradient: "linear-gradient(135deg, #fbbf24, #d97706)",
  },
  {
    id: "vietnam",
    name: "Vietnam",
    country: "Vietnam",
    style: "budget",
    continent: "Asia",
    emoji: "🍜",
    tagline: "Pho, Ha Long Bay & motorbike tours",
    gradient: "linear-gradient(135deg, #fb923c, #ea580c)",
  },
  {
    id: "albania",
    name: "Albania",
    country: "Albania",
    style: "budget",
    continent: "Europe",
    emoji: "🏔️",
    tagline: "Hidden beaches & affordable Alps",
    gradient: "linear-gradient(135deg, #a78bfa, #7c3aed)",
  },
  {
    id: "dubai",
    name: "Dubai",
    country: "UAE",
    style: "luxury",
    continent: "Asia",
    emoji: "🏙️",
    tagline: "Skyscrapers, desert safaris & malls",
    gradient: "linear-gradient(135deg, #f59e0b, #b45309)",
  },
  {
    id: "switzerland",
    name: "Switzerland",
    country: "Switzerland",
    style: "luxury",
    continent: "Europe",
    emoji: "🏔️",
    tagline: "Alps, chocolate & luxury trains",
    gradient: "linear-gradient(135deg, #60a5fa, #2563eb)",
  },
  {
    id: "seychelles",
    name: "Seychelles",
    country: "Seychelles",
    style: "luxury",
    continent: "Africa",
    emoji: "🐢",
    tagline: "Pristine beaches & nature reserves",
    gradient: "linear-gradient(135deg, #2dd4bf, #0d9488)",
  },
  {
    id: "iceland",
    name: "Iceland",
    country: "Iceland",
    style: "adventure",
    continent: "Europe",
    emoji: "🌋",
    tagline: "Volcanoes, glaciers & northern lights",
    gradient: "linear-gradient(135deg, #818cf8, #4f46e5)",
  },
  {
    id: "nepal",
    name: "Nepal",
    country: "Nepal",
    style: "adventure",
    continent: "Asia",
    emoji: "🗻",
    tagline: "Everest treks & Himalayan culture",
    gradient: "linear-gradient(135deg, #94a3b8, #475569)",
  },
  {
    id: "peru",
    name: "Peru",
    country: "Peru",
    style: "adventure",
    continent: "South America",
    emoji: "🦙",
    tagline: "Machu Picchu & Amazon rainforest",
    gradient: "linear-gradient(135deg, #f87171, #dc2626)",
  },
  {
    id: "costa_rica",
    name: "Costa Rica",
    country: "Costa Rica",
    style: "adventure",
    continent: "North America",
    emoji: "🦜",
    tagline: "Rainforests, zip-lines & wildlife",
    gradient: "linear-gradient(135deg, #4ade80, #16a34a)",
  },
  {
    id: "italy",
    name: "Italy",
    country: "Italy",
    style: "culture",
    continent: "Europe",
    emoji: "🎨",
    tagline: "Renaissance art, pasta & history",
    gradient: "linear-gradient(135deg, #f97316, #c2410c)",
  },
  {
    id: "egypt",
    name: "Egypt",
    country: "Egypt",
    style: "culture",
    continent: "Africa",
    emoji: "🏛️",
    tagline: "Pyramids, Nile cruises & ancient wonders",
    gradient: "linear-gradient(135deg, #eab308, #a16207)",
  },
  {
    id: "india",
    name: "India",
    country: "India",
    style: "culture",
    continent: "Asia",
    emoji: "🕌",
    tagline: "Taj Mahal, spices & vibrant festivals",
    gradient: "linear-gradient(135deg, #e879f9, #c026d3)",
  },
  {
    id: "portugal",
    name: "Portugal",
    country: "Portugal",
    style: "family",
    continent: "Europe",
    emoji: "⚓",
    tagline: "Coastal towns, castles & kid-friendly beaches",
    gradient: "linear-gradient(135deg, #38bdf8, #0369a1)",
  },
  {
    id: "morocco",
    name: "Morocco",
    country: "Morocco",
    style: "family",
    continent: "Africa",
    emoji: "🐪",
    tagline: "Medinas, souks & Sahara desert camps",
    gradient: "linear-gradient(135deg, #fb7185, #e11d48)",
  },
  {
    id: "canada",
    name: "Canada",
    country: "Canada",
    style: "family",
    continent: "North America",
    emoji: "🍁",
    tagline: "National parks, lakes & outdoor fun",
    gradient: "linear-gradient(135deg, #ef4444, #b91c1c)",
  },
];

export const STYLE_FILTERS = [
  { id: "all", label: "All Styles" },
  { id: "relaxation", label: "Relaxation" },
  { id: "budget", label: "Budget" },
  { id: "luxury", label: "Luxury" },
  { id: "adventure", label: "Adventure" },
  { id: "culture", label: "Culture" },
  { id: "family", label: "Family" },
];
