export async function copyPlanToClipboard(plan) {
  if (!plan) return false;
  try {
    await navigator.clipboard.writeText(plan);
    return true;
  } catch {
    return false;
  }
}

export function downloadPlanAsMarkdown(plan, destination = "destination") {
  if (!plan) return;
  const slug = destination.toLowerCase().replace(/\s+/g, "-").slice(0, 30);
  const date = new Date().toISOString().slice(0, 10);
  const filename = `travel-plan-${slug}-${date}.md`;
  const header = `# Travel Plan: ${destination}\n\n_Generated by Smart Travel Planner on ${date}_\n\n---\n\n`;
  const blob = new Blob([header + plan], { type: "text/markdown" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

export function extractLastPlan(messages) {
  for (let i = messages.length - 1; i >= 0; i--) {
    const m = messages[i];
    if (m.role === "agent" && m.content && !m.isQuestion && !m.isEmailAsk && m.content.length > 100) {
      return m.content;
    }
  }
  return null;
}
